//Verification types
export const VerificationTypes = {
  EMAIL_VERIFICATION: 'EMAIL_VERIFICATION',
  PHONE_VERIFICATION: 'PHONE_VERIFICATION',
  PASSWORD_RESET: 'PASSWORD_RESET',
  TRANSACTION_PIN: 'TRANSACTION_PIN',
};